"""empty message

Revision ID: 06c34cf49dc0
Revises: dce9c92f5bfc
Create Date: 2016-10-18 14:00:02.758157

"""

# revision identifiers, used by Alembic.
revision = '06c34cf49dc0'
down_revision = 'dce9c92f5bfc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reported_cases', sa.Column('month', sa.String(length=20), nullable=True))
    op.add_column('reported_cases', sa.Column('year', sa.String(length=20), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reported_cases', 'year')
    op.drop_column('reported_cases', 'month')
    ### end Alembic commands ###
