"""empty message

Revision ID: cb180e3ed2a4
Revises: 25e04c860601
Create Date: 2016-10-20 12:01:45.374191

"""

# revision identifiers, used by Alembic.
revision = 'cb180e3ed2a4'
down_revision = '25e04c860601'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_notes', sa.Column('created_by', sa.String(length=100), nullable=True))
    op.add_column('case_notes', sa.Column('date_created', sa.Date(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_notes', 'date_created')
    op.drop_column('case_notes', 'created_by')
    ### end Alembic commands ###
