"""empty message

Revision ID: ea3bab0254d5
Revises: 664d49654085
Create Date: 2016-10-22 09:57:16.314196

"""

# revision identifiers, used by Alembic.
revision = 'ea3bab0254d5'
down_revision = '664d49654085'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('first_name', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('member_since', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('other_names', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'other_names')
    op.drop_column('users', 'member_since')
    op.drop_column('users', 'last_seen')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
